// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/website_starter/PlasmicGlobalContextsProvider";
import { ScreenVariantProvider } from "../components/plasmic/website_starter/PlasmicGlobalVariant__Screen";
import { PlasmicAdmin } from "../components/plasmic/website_starter/PlasmicAdmin";
import { useRouter } from "next/router";
import useSWR from "swr";

function Admin() {
  const { data, mutate } = useSWR("orders", async () => 
    (await (await fetch("/api/hello?newOrder=all")).json())
  )
  return (
    <GlobalContextsProvider>
      <ph.PageParamsProvider
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <PlasmicAdmin
          onFinish={async ({ name, barraca }) => {
            await fetch(`/api/hello`, {
              method: "POST",
              body: JSON.stringify({name, barraca})
            });
            mutate();
          }}
          orders={data}
          onSubmit={async (id) => {
            await fetch(`/api/hello?id=${id}`, {
              method: "DELETE"
            });
            mutate()
          }}
        />
      </ph.PageParamsProvider>
    </GlobalContextsProvider>
  );
}

export default Admin;
